part/19:
alex-b1/rack pull request #1
Opened 2021-05-26 08:20 UTC by alex-b1

2021-05-26 19:29 UTC, BubuntuClu requested changes

2021-05-26 19:29 UTC, BubuntuClu commented on app.rb
> +  def response
`response` не совсем правильное название метода. ты тут делаешь какую-то логику, а ответ у тебя идет на 7ой строке. стоит сделать метод `response` и в нем отдавать уже ответ используя Rack::Response

2021-05-26 19:29 UTC, BubuntuClu commented on app.rb
> +    @status_code = 200
очень много инстанс-переменных, которые тут не нужны вообще. парсер даты, статусы, сообщения, все это можно явно передать в метод `response(code, message)`
в случае успеха `response(200, handler.time)` и тд

2021-05-26 19:29 UTC, BubuntuClu commented on handler.rb
> +    formats = @correct.map { |i| TIME_LIST[i.to_sym]}
у тебя получается два раза перебор параметров идет. сначала в `check_format`, а потом тут в методе map. можно за один раз сразу собрать нужные данные, уменьшить сложность алгоритма.
так же ты выделяешь лишнюю память. ты сначала создаешь два массива `@correct, @incorrect`, а потом еще один `formats = @correct.map `. прикинь у тебя `correct` занял бы один ГБ в памяти, а ты потом еще map'ом еще один ГБ съел) очень не оптимально

2021-05-27 06:59 UTC, BubuntuClu approved these changes

2021-05-27 06:59 UTC, BubuntuClu commented on app.rb
> +    [code, { 'Content-Type' => 'text/plain' }, ["#{message}\n"]]
Rack::Response заюзать бы для ответа

2021-05-27 06:59 UTC, BubuntuClu commented on handler.rb
> +    @correct = []
это же код инициализации. его туда и стоит поместить

2021-05-27 07:03 UTC, alex-b1 commented on app.rb
> +    [code, { 'Content-Type' => 'text/plain' }, ["#{message}\n"]]
вызывал Rack::Response.new(...),код с ошибкой падал, undefined method `to_i' for #<Rack::Response:0x00007f50cc086910> Did you mean? to_s to_a , не нашел причину, решил так оставить

2021-05-28 21:32 UTC, merged